# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Kingfisher'
pod 'Alamofire'
pod 'SwiftyJSON'


pod 'CSSwiftExtension'
pod 'Hero'


pod 'RxSwift'
pod 'RxCocoa'
pod 'RxDataSources'


target 'Eyepetizer-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Eyepetizer-Swift

  target 'Eyepetizer-SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
